-- AlterTable
ALTER TABLE `team` MODIFY `district` ENUM('NONE', 'MUEANG', 'SI_MUEANG_MAI', 'KHONG_CHIAM', 'KHUEANG_NAI', 'KHEMMARAT', 'DET', 'NA_CHALUAI', 'NAM_YUEN', 'BUNTHARIK', 'TRAKAN', 'KUT_KHAOPUN', 'MUANG_SAM_SIP', 'WARIN', 'PHIBUN', 'TAN_SUM', 'PHO_SAI', 'SAMRONG', 'DON_MOT_DAENG', 'SIRINDHORN', 'THUNG_SI_UDOM', 'SI_LAK_CHAI', 'NAM_KHUN', 'LAO_SUEA_KOK', 'SAWANG_WIRAWONG') NOT NULL;

-- AlterTable
ALTER TABLE `user` MODIFY `district` ENUM('NONE', 'MUEANG', 'SI_MUEANG_MAI', 'KHONG_CHIAM', 'KHUEANG_NAI', 'KHEMMARAT', 'DET', 'NA_CHALUAI', 'NAM_YUEN', 'BUNTHARIK', 'TRAKAN', 'KUT_KHAOPUN', 'MUANG_SAM_SIP', 'WARIN', 'PHIBUN', 'TAN_SUM', 'PHO_SAI', 'SAMRONG', 'DON_MOT_DAENG', 'SIRINDHORN', 'THUNG_SI_UDOM', 'SI_LAK_CHAI', 'NAM_KHUN', 'LAO_SUEA_KOK', 'SAWANG_WIRAWONG') NOT NULL DEFAULT 'NONE';
